version: '3'
services:
  middleware_manager:
    #image: courchesnea/dt-middleware:test
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      middleware_parameters: |
        episodes_per_scenario: 1
        episode_length_s: 100.0
        min_episode_length_s: 1.0
        seed: 42
        physics_dt: 0.05
        max_failures: 2
        agent_in: /fifos3/agent-in
        agent_out: /fifos3/agent-out
        sim_in: /fifos3/simulator-out
        sim_out: /fifos3/simulator-in
        sm_in: None
        sm_out: None
        timeout_initialization: 15
        timeout_regular: 30
    volumes:
      - ./.fifos:/fifos3

  simulator:
    #image: duckietown/challenge-aido_lf-simulator-gym:daffy-aido4
    image: courchesnea/dt-simbridge:test
    environment:
      AIDONODE_DATA_IN: /fifos3/simulator-in
      AIDONODE_DATA_OUT: /fifos3/simulator-out
    volumes:
      - ./.fifos:/fifos3

        #  agent:
        #    image: courchesnea/dt-random:test
        #    #image: duckietown/challenge-aido_lf-template-random:daffy
        #    environment:
        #      AIDONODE_DATA_IN: /fifos3/agent-in
        #      AIDONODE_DATA_OUT: /fifos3/agent-out
        #    volumes:
        #      - ./.fifos:/fifos3
